In [1]:
cd ..

/home/pierre/git/semisupervised


/home/pierre/miniconda3/envs/semisupervised/lib/python3.12/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [10]:
from ucimlrepo import fetch_ucirepo, list_available_datasets
from sklearn import svm
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [39]:
list_available_datasets()
heart_disease = fetch_ucirepo(name='Wine Quality')

-------------------------------------
The following datasets are available:
-------------------------------------
Dataset Name                                                                            ID    
------------                                                                            --    
Abalone                                                                                 1     
Adult                                                                                   2     
Annealing                                                                               3     
Audiology (Standardized)                                                                8     
Auto MPG                                                                                9     
Automobile                                                                              10    
Balance Scale                                                                           12    
Balloons                       

In [40]:
X = heart_disease.data.features
y = heart_disease.data.targets

In [41]:
X

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
6492     11.2  
6493      9.6  
6494      9.4  
6495     12.8  
6496     11.8  

[6497 rows x 11 columns]

In [42]:
X_clean = imp.fit_transform(X)

In [51]:
X_clean.shape

(6497, 11)

In [49]:
np.mean(X_clean, axis=0)

(11,)

In [55]:
np.cov(X_clean, rowvar=False)

(11, 11)

In [43]:
regr = svm.SVR()
regr.fit(X_clean, y)

/home/pierre/miniconda3/envs/semisupervised/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [44]:
regr.predict([X_clean[3]])

array([5.66862278])

In [28]:
import torch
t = torch.ones(13)

In [29]:
t

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
regr.predict([t])

array([0.92062652])

In [38]:
float(np.max(y))

4.0

In [56]:
import scipy
m, cov = np.mean(X_clean, axis=0), np.cov(X_clean, rowvar=False)
B = scipy.linalg.cholesky(cov)

In [57]:
B

array([[ 1.29643376e+00,  3.60567471e-02,  4.71463069e-02,
        -5.32784958e-01,  1.04468368e-02, -5.01838415e+00,
        -1.85987367e+01,  1.37612098e-03, -4.06310013e-02,
         4.45774399e-02, -1.13846152e-01],
       [ 0.00000000e+00,  1.60639595e-01, -6.68764271e-02,
        -8.36198788e-01,  1.11958804e-02, -5.28696462e+00,
        -1.98352259e+01,  5.24887778e-04,  5.22044129e-02,
         2.44586541e-02, -2.04575304e-02],
       [ 0.00000000e+00,  0.00000000e+00,  1.20091844e-01,
         5.63624968e-01,  3.78668440e-03,  1.88519900e+00,
         9.60930432e+00,  1.00953620e-04, -1.91453928e-02,
         6.23909716e-03,  1.81572916e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.61908380e+00, -1.88317867e-03,  5.59947978e+00,
         2.19380067e+01,  1.94800544e-03, -3.71722108e-02,
        -1.96897508e-02, -4.60602776e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.12247298e-02, -2.00455539e-01,
  

In [59]:

B_inv = scipy.linalg.lapack.dtrtri(B)

In [63]:
np.dot(B_inv[0], B)

array([[ 1.00000000e+00, -6.33307238e-19, -7.08199436e-20,
        -4.40638391e-17,  2.58424605e-20,  3.73369376e-16,
         1.90743384e-15, -3.07981088e-20,  7.16624949e-18,
        -1.16570414e-18, -1.29896622e-16],
       [ 0.00000000e+00,  1.00000000e+00, -5.72811153e-18,
         2.60840707e-16,  3.20933961e-18,  3.71445544e-15,
        -4.61519245e-16, -4.67706250e-19,  8.31759280e-18,
        -7.43759802e-18, -5.48391657e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.15372464e-16,  1.91983108e-19, -3.40697373e-15,
        -1.09402623e-15,  9.20228473e-21, -2.05953253e-17,
        -2.85944361e-18,  4.77044126e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00, -3.10459902e-20, -1.04075045e-16,
         1.29028020e-16,  4.53544356e-20, -1.06949722e-18,
         7.02299381e-19, -6.90501416e-18],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  8.88585877e-16,
  

In [62]:
B_inv

(array([[ 7.71346776e-01, -1.73134498e-01, -3.99234175e-01,
          1.06342616e-01, -1.41160702e-01,  2.04740647e-01,
          1.89455685e-01, -6.53708816e-01,  7.06127289e-01,
         -5.78218766e-02, -1.04444788e+00],
        [ 0.00000000e+00,  6.22511528e+00,  3.46662565e+00,
          7.03939834e-01, -2.61001519e+00,  1.45447576e+00,
          7.64103626e-01, -2.02654616e+00, -5.27770954e-01,
          2.56457410e-01, -2.58699406e+00],
        [ 0.00000000e+00,  0.00000000e+00,  8.32696012e+00,
         -1.01606354e+00, -1.07110612e+00, -6.78606264e-01,
         -1.29028315e+00,  1.17897835e+00,  1.28006935e-01,
         -6.75843694e-01, -8.06338943e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          2.16493150e-01,  1.30568074e-02, -8.02937368e-02,
         -7.60158026e-02, -2.68123159e-01,  1.95838864e-01,
          6.50094319e-02, -3.81593272e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  3.20258977e+01,  

In [77]:
X_clean_norm = np.dot(X_clean - m, B_inv[0])

In [78]:
np.cov(X_clean_norm, rowvar=False)

array([[ 1.00000000e+00, -1.37000427e-16, -3.76272631e-16,
         6.34413157e-17, -1.41102237e-16,  2.09465723e-16,
         1.76104342e-16, -1.11459829e-15,  8.92006775e-16,
         1.14303750e-16, -2.08795761e-15],
       [-1.37000427e-16,  1.00000000e+00, -3.67795559e-16,
         3.69162828e-17,  3.41817434e-16, -1.95793026e-16,
         9.84434209e-18,  1.85948684e-17,  3.41817434e-17,
         9.51619735e-17, -5.22297039e-17],
       [-3.76272631e-16, -3.67795559e-16,  1.00000000e+00,
        -9.35212499e-17,  3.13378223e-16, -3.14403676e-16,
        -6.23474999e-17,  5.06436710e-16, -1.43238596e-16,
        -1.20319737e-17,  6.88762129e-16],
       [ 6.34413157e-17,  3.69162828e-17, -9.35212499e-17,
         1.00000000e+00,  1.39461513e-17, -1.64619276e-16,
        -1.39461513e-17, -3.65197746e-16, -7.00042104e-17,
         2.05637368e-16, -7.35864571e-16],
       [-1.41102237e-16,  3.41817434e-16,  3.13378223e-16,
         1.39461513e-17,  1.00000000e+00,  1.60244013e-16,
  

In [75]:
np.cov(X_clean_norm, axis=0)

array([ 6.16571080e-15, -3.97584587e-14,  5.30790844e-14, -2.94392800e-15,
        1.45739457e-13, -3.71694876e-16, -9.83001070e-17,  4.04247087e-13,
       -4.59181544e-15, -1.01722882e-15,  1.38120835e-15])

In [ ]:
m, cov = np.mean(X_clean, axis=0), np.cov(X_clean, rowvar=False)


In [67]:
X_clean

array([[ 7.4 ,  0.7 ,  0.  , ...,  3.51,  0.56,  9.4 ],
       [ 7.8 ,  0.88,  0.  , ...,  3.2 ,  0.68,  9.8 ],
       [ 7.8 ,  0.76,  0.04, ...,  3.26,  0.65,  9.8 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [65]:
m

array([7.21530706e+00, 3.39666000e-01, 3.18633215e-01, 5.44323534e+00,
       5.60338618e-02, 3.05253194e+01, 1.15744574e+02, 9.94696634e-01,
       3.21850085e+00, 5.31268278e-01, 1.04918008e+01])